### PR TITLE
apply nodeview for tiptap

### PR DESCRIPTION
**Pull request by epilo9er**
PR for issue, #1 .

A few people have tested the code and found no bugs. 
There seems to be a lot of people who need it, so we create a PR.

### CODE REVIEW

**Review by Myroslav-mint — APPROVED** [review]

**Review by mirus-ua — APPROVED** [review]

**Comment by mirus-ua** [comment]
It would be nice to update the `readme` with an example

**Comment by lxsmnsyc** [comment]
Once all is good I will make a minor version release.

**Comment by CamilleHbp** [comment]
Hello! It's been almost 6 months since the PR was made, any news on the merge? Thanks! 🙏

**Comment by lxsmnsyc** [comment]
well I can make a release for this. My previous comment was intended to make sure that the PR is good and ready for merging, but there was no follow up, although I might have not been clear.

**Pull request closed without merging**
